#!/bin/bash

ahrb=/nfs/turbo/ahrb-data

source $ahrb/Scripts/source/ahrb_config

work_dir=/nfs/turbo/ahrb-data/work_dir

fsl=/nfs/turbo/ahrb-data/FSL_Analysis


#Quality Check file
Image_Q=$fsl/QA/$1/secondlevel_report.csv

#Subject list
list=$fsl/QA/$1/secondlevel_review.txt

# Today's date
date=$(date)

echo
echo "Hi ${USER}, " 
echo "Weclome to the FSL Second Level report review script!"
echo "This script will cycle through subjects and their runs in: $list "
echo "Reminder:"
echo "		1) Review alginment between the two runs look for missing"
echo "		   voxels in run 1 (red) or run 2) yellow"
echo "		2) Then confirm activation maps, that nothing weird is   "
echo "		   happening. e.g., outside of field. "
echo "*Note the issues with 1 or 2 			 "
echo 
echo 

## Script pauses or 'sleeps' for 5 seconds, before continuing.
sleep 5 

# The below cycles through all subjects and their folders.
# It opens the feat report.html for each subject's run in firefox
# The script prompts user to indicate if there were issues with the 1-3 items discussed above
# It uses the read value to collect the response, that'll then be exported into a .csv for closer examination

#For each subject, perform.....for each run (01 02)
for subj in $(cat $list ) ; do
	subj_header $subj
	echo

        if [ -s $fsl/Subjects/$subj/model/SecondLevel/SecondLevel.gfeat/report.html ] ; then
	
	firefox $fsl/Subjects/$subj/model/SecondLevel/SecondLevel.gfeat/report.html &

sleep 1

        
# Input for registration/normalization. Provide inpurt to 'read' if yes, request more info, no, proceeds, e, exits.
	echo -n "Any problems with reg of two runs [y= yes; n = no; to e = exit ]? "
                read regist
		# take the answer provided, cut to take only the first letter, upper and lowercase        
	        answer=$(echo $regist | cut -c 1 | tr '[A-Z]' '[a-z]')
       
	case $regist in
                'n')
                        indent "$subj Reg of runs = ${gre}GOOD${recol}"
                        echo
                        indent "${subj}\tRegRuns\trun_${run}.feat\tGood\t${date}\t${USER}" >> $Image_Q
                        ;;
                'y')
                        indent "You indicated that Reg of runs for $subj = BAD"
                       
			echo "Please provide a brief description of problem. Only use spaces and periods." 
			echo -n "Hit Return when complete.  "
                       
			read registprob
                        indent "$subj Reg of runs = ${bred}BAD. Reason: $registprob${recol}"
                        indent "${subj}\tRegRuns\trun_${run}.feat\tBad\t${date}\t${USER}\t$registprob" >> $Image_Q
                        echo
                        ;;
                'e')
			echo                        
			echo "....Quitting"
                        exit 1
                        ;;
        esac
echo

# Input for MCFLIRT/Motion pre-stats tab
	echo -n "Activation maps look okay? e.g., not outside of brain or where not expected [y= yes; n = no; to e = exit ]? "
                read Activation
		# take the answer provided, cut to take only the first letter, upper and lowercase        
	        answer=$(echo $Activation | cut -c 1 | tr '[A-Z]' '[a-z]')

	case $Activation in
                'n')
                        indent "$subj Activation Maps = ${gre}GOOD${recol}"
                        echo
                        indent "${subj}\tActivation\trun_${run}.feat\tGood\t${date}\t${USER}" >> $Image_Q
                        ;;
                'y')
                        indent "You indicated that Activation Maps = BAD"
                       
			echo "Please provide a brief description of problem. Only use spaces and periods." 
			echo -n "Hit Return when complete.  "
                        
			read Activationresp
                        indent "$subj Activation Maps = ${bred}BAD. Reason: $Activationresp${recol}"
                        indent "${subj}\tActivation\trun_${run}.feat\tBad\t${date}\t${USER}\t$Activationresp" >> $Image_Q
                        echo
                        ;;
                'e')
			echo                        
			echo "....Quitting"
                        exit 1
                        ;;
        esac
echo

	else
                indent "${bred}For $subj - no *SecondLevel.gfeat/report.html${recol}"
        fi

# Remove subject from list before continuing.
sed -i "/${subj}/d" $list

togo=$(cat $list | wc -l )
echo
echo "${togo} subjects to go in the list"
echo

done
