#!/bin/bash
## This script is used to loop through a list of subjects a review MID/FACES/ANATOMY image files
## .nii files are opened using fslview view
## At different stages of the script, the "echo -n" indicates a question that will require a response
## the subsequent "read..." will capture this value into the appropriate variable
## In some cases of y/n or good/bad, this response will  garner information about the quality of the file
## the info for the subject,  task, run, quality and/or notes will be written to the Imge_Q file
## at the end of each subject forloop, using the sed command, that subject will be removed from the list
## this will prevent users from having to go back and update the $list variable .txt file


#Colors
rcol='\e[0m'
blub='\e[1;34m'
ired='\e[1;91m'
gre='\e[1;32m'

#Set working directory
work_dir=/nfs/turbo/ahrb-data/work_dir

person=$(whoami)
date=$(date)

#Quality Check file
Image_Q=/nfs/turbo/ahrb-data/Demidenko/scripts/ImageQuality.csv

#Subject list
list=/nfs/turbo/ahrb-data/Demidenko/scripts/ImageQ_subjects.txt

#For each subject, perform.....for each run (01 02)
echo "Checking subjects listed in ImageQ_subjects.txt file [located in $list]"
echo
for subject in $(cat $list ) ; do
	echo -e "${blub}Reviewing quality checks for subject $subject....................... ${rcol}"
	for run in 01 02 ; do
	echo "Checking MID for $Subject..."
	if [ -s $work_dir/$subject/func/mid/run_$run/run_${run}.nii ] ; then
		fslview $work_dir/$subject/func/mid/run_$run/run_${run}.nii
## The following echo -n function garners a response that is then used in "read answer"
## This variable is that used in the subsequent if [] command to evalue the response and request/write info
## to the .txt file accordingly. The items written include all subject/file info, quality, date and person
		echo -n "Any problems with the MID run_$run *.nii for $subject? [y= yes; n = no; to exit = ctrl+z]? " 
		read answer
		if [ "$answer" != "${answer#[Nn]}" ] ; then
		echo -e "${gre}$subject MID run_$run *nii = GOOD${rcol}" 
		echo "Great, thank you."
		echo "${subject}; MID; run_${run}; run_${run}.nii; Good; ${date}; ${person}" >> $Image_Q
		else
		echo "You indicated that $subject MID run_$run *.nii was BAD" 
		echo -n "Please provide a brief description of problem. Only use spaces and periods. Hit Return when complete.  "
		read problem
		echo -e "${ired}$subject MID run_$run *nii = BAD. Reason: $problem${rcol}"
		echo "${subject}; MID; run_${run}; run_${run}.nii; Bad; ${date}; ${person}; $problem" >> $Image_Q
		echo "Great, thank you."
		fi
	else
		echo -e "${ired}For $subject MID run_$run, no run_$run.nii file found.${rcol}"
	fi
## Same as above, but evalues whether you wish to continue onto the Faces
	echo
	echo -n -e "${gre}Continue checking next participants task/run ${rcol} (y/n)? "
	read cont
	if [ "$cont" != "${cont#[Yy]}" ] ; then
	echo "Continuing....."
	else 
	echo
	echo "Exiting image quality check script...."
	exit 1
	fi
## If elected to continue, script begins checing faces run 01 02 
	echo 
	echo "Checking Faces...."
        if [ -s $work_dir/$subject/func/faces/run_$run/run_${run}.nii ] ; then
                fslview $work_dir/$subject/func/faces/run_$run/run_${run}.nii
                echo -n "Any problems with the FACES run_$run *.nii for $subject? [y= yes; n = no; to exit = ctrl+z]? " 
                read answer
                if [ "$answer" != "${answer#[Nn]}" ] ; then
                echo -e "${gre}$subject FACES run_$run *nii = GOOD${rcol}" 
                echo "Great, thank you."
                echo "${subject}; FACES; run_${run}; run_${run}.nii; Good; ${date}; ${person}" >> $Image_Q
                else
                echo -e "${ired}You indicated that $subject FACES run_$run *.nii was BAD${rcol}" 
                echo -n "Please provide a brief description of problem. Only use spaces and periods. Hit Return when complete.  "
                read problem
                echo "$subject FACES run_$run *nii = BAD. Reason: $problem"
                echo "${subject}; FACES; run_${run}; run_${run}.nii; Bad; ${date}; ${person}; $problem" >> $Image_Q
                echo "Great, thank you."
                fi
        else
                echo -e "${ired}For $subject FACES run_$run, no run_$run.nii file found.${rcol}"
                echo
        fi
        echo -n "Continue checking next participants task/run (y/n)? "
        read cont
	if [ "$cont" != "${cont#[Yy]}" ] ; then
        echo "Continuing....."
        else 
        echo
        echo "Exiting image quality check script...."
        exit 1
        fi
	done

##Next proceeds to the ANATOMICAL checks -- reviewing the homogeneity correct t1spgr and t1overlay files
	echo
	echo "Continuing on Checking Anatomical..."
for anat in $(ls $work_dir/$subject/anatomy) ; do
	if [ -s $work_dir/$subject/anatomy/$anat/h${anat}.nii ] ; then
                fslview $work_dir/$subject/anatomy/$anat/h${anat}.nii
                echo -n "Any problems with the anatomy h${anat}.nii file for $subject? [y= yes; n = no; to exit = ctrl+z]? " 
                read answer
                if [ "$answer" != "${answer#[Nn]}" ] ; then
                echo -e "${gre}$subject ANATOMY $anat h${anat}.nii = GOOD${rcol}" 
                echo "Great, thank you."
                echo "${subject}; ANATOMY; ${anat}; h${anat}.nii; Good; ${date}; ${person}" >> $Image_Q
                else
                echo -e "${ired}You indicated that $subject ANATOMY $anat h${anat}.nii was BAD${rcol}" 
                echo -n "Please provide a brief description of problem. Only use spaces and periods. Hit Return when complete.  "
                read problem
                echo "$subject ANATOMY $anat h${anat}.nii = BAD. Reason: $problem"
                echo "${subject}; ANATOMY; $anat; h${anat}.nii; Bad; ${date}; ${person}; $problem" >> $Image_Q
                echo "Great, thank you."
                fi
        else
                echo -e "${ired}For $subject Anatomical  $anat, no h${anat}.nii file found.${rcol}"
                echo
        fi
	done

## Confirms that the MID, FACES & ANATOMY checks are completed
## sed -i command removes the $subject from the .txt file that is assigned to the $list variable
echo "MID, FACES & Anat checks completed for $subject -- removed from subject list file."
sed -i "/${subject}/d" $list

## Once subject is removed from the script, script asks whether or not to continue onto the next subect.
  echo -n "Continue on to next participant (y/n)? "
        read cont
        if [ "$cont" != "${cont#[Yy]}" ] ; then
        echo "Continuing....."
        else 
        echo
        echo "Exiting image quality check script...."
        exit 1
        fi
done
