#!/bin/bash

# This script will download a new subject, set the permissions, and create
# a symlinked version in the work_dir.

work_dir=/nfs/turbo/ahrb-data/work_dir
archive_dir=/nfs/turbo/ahrb-data/archive_dir
server=singer.engin.umich.edu
server_data=/export/archive/trailer

if [ $# -lt 1 ] ; then
    echo "This script requires a subject ID to run."
    echo "Usage:"
    echo
    echo "$0 <subject ID number only>"
    echo 
    echo "For example, to retrieve dpk16ahr203704_04327, enter"
    echo
    echo $0 203704_04327
    echo
    echo "dpk16ahr will be prepended automatically"
    echo
    exit 1
fi

subj_id="dpk16ahr$1"

echo "Retrieving subject $subj_id from ${server}. . ."

from_dir=$(ssh $server -l fmriuser ls -d $server_data/$subj_id)

if [ $from_dir ! = $server_data/$subj_id ] ; then
    echo "Mismatch.  Exiting."
    exit 1
else
    rsync -av fmriuser@$server:$server_data/$subj_id $archive_dir
    rc=$?
fi

if [$rc -ne 0 ] ; then
    echo "Rsync exited with an error.  Please check results."
fi

echo "Setting subject dir to read-only"
chmod -R -w $archive_dir/$subj_id

echo "Creating recursive symbolic links in #work_dir"
cp -Rs $archive_dir/$subj_id $work_dir

###################################
# email confirmation when copy complete
##################################

person=$(whoami)
email=${whoami}@umich.edu
echo "Copying of data initiated by $person has completed for $subj_id" | mail -s "Copy from MRI to AHRB server complete" "$email"
