#!/bin/bash

if [ $# -lt 1 ] ; then
    echo "This script requires a subject ID to run."
    echo "Usage:"
    echo
    echo "$0 <subject ID number only>"
    echo 
    echo "For example, to create a workdir for dpk16ahr203704_04327, enter"
    echo
    echo $0 203704_04327
    echo
    echo "dpk16ahr will be prepended automatically"
    echo
    exit 1
fi
subject_id="dpk16ahr$1"

#creates fmri-lab variable $archieve and $work for work_dir to use downstream
archive=/nfs/turbo/ahrb-data/fmri-lab
work=/nfs/turbo/ahrb-data/work_dir

# Set the umask explicitly here so that group write gets properly
# set on the work_dir folders.
umask 002

#For specified  subject in the archieve directory, checks directories (if [ -d ..]) and 
#creates symbolic links (cp -rs) for  subject in $archive in the $work directory
	if [ -d $archive/$subject_id ] ; then
    # Copy, recursively the folders and create symlinks to all files
   
    echo
    echo "Creating working directory for subject $subject_id. . ."
    cp -rs $archive/$subject_id $work

    echo "All done."
    echo
    ls -ld $work/$subject_id
else
    echo
    echo "Whoops!  The folder you wanted copied"
    echo
    echo "    $archive/$subject_id"
    echo
    echo "does not exist."
    exit 1
fi
