#!/bin/bash

ahrb=/nfs/turbo/ahrb-data

source $ahrb/Scripts/source/ahrb_config

work_dir=/nfs/turbo/ahrb-data/work_dir


#Quality Check file
Image_Q=/nfs/turbo/ahrb-data/FSL_Analysis/QA_skullstrip_${1}.csv

#Subject list
list=/nfs/turbo/ahrb-data/FSL_Analysis/sub_list_${cw}.txt

# Today's date
date=$(date)

#For each subject, perform.....for each run (01 02)
echo "Checking subjects in $list "
echo
for subject in $(cat $list ) ; do
	subj_header $subject

        if [ -s $work_dir/$subject/anatomy/t1spgr_208sl/t1spgr_208sl_brain.nii.gz ] ; then
                
		whole=$work_dir/$subject/anatomy/t1spgr_208sl/t1spgr_208sl.nii
		stripped=$work_dir/$subject/anatomy/t1spgr_208sl/t1spgr_208sl_brain.nii.gz

			fslview $whole $stripped -l Cool -b 0,10 -t .3
        
	echo -n "Any skull stripping problem? [y= yes; n = no; to e = exit ]? "
                read answer
		# take the answer provided, any only cut to take first letter, upper and lowercase        
	        answer=$(echo $answer | cut -c 1 | tr '[A-Z]' '[a-z]')
       
	case $answer in
                'n')
                        indent "$subject skull stripping = ${gre}GOOD${recol}"
                        indent "Great, thank you."
                        indent "${subject}\tSkull_Stripping\tt1spgr_208sl_brain.nii.gz\tGood\t${date}\t${USER}" >> $Image_Q
                        ;;
                'y')
                        indent "You indicated that skull stripping for $subject = BAD"
                        echo -n "Please provide a brief description of problem. Only use spaces and periods. Hit Return when complete.  "
                        read problem
                        indent "$subject Skull Stripping = ${bred}BAD. Reason: $problem${recol}"
                        indent "${subject}\tSkull_Stripping\tt1spgr_208sl_brain.nii.gz\tBad\t${date}\t${USER}\t$problem" >> $Image_Q
                        indent "Great, thank you."
                        ;;
                'e')
			echo                        
			echo "....Quitting"
                        exit 1
                        ;;
        esac
        else
                indent "${bred}For $subject - no *_brain.nii.gz file found.${recol}"
        fi


# Remove subject from list before continuing.
sed -i "/${subject}/d" $list

done
