#!/bin/bash
# Source content
source /nfs/turbo/ahrb-data/Scripts/source/ahrb_config

# Calling ROI that is located in ../masks/ folders
roi=/nfs/turbo/ahrb-data/Demidenko/masks/$1

# con_####.nii image name
con=$2

# Location for First level subject directories
First_level=/nfs/turbo/ahrb-data/Analysis/FirstLevel/output/mid

# When the dimensions are incorrect, run below in terminal on ROI & con_####.nii image
#3dresample -master  $con -input $roi -prefix $roi 

# Confirm that inputs values were provided $1 = ROI ; $2 = con immage

if [ $# -lt 2 ] ; then
		echo
		echo
		echo "This script requires an ROI and CON .nii file name"
		echo "Example: to run this script for R_Amyg.nii & con_0001.nii,  enter:"
		indent "${gre}$0 ${recol}${bred}R_amyg.nii con_0001.nii${recol}"
		echo "ROI's to select from:" 
		# List the masks located in the ../masks/ folder
		for roi in $(ls /nfs/turbo/ahrb-data/Demidenko/masks) ; do
		indent "$roi"
		done
		echo
		
	exit
fi

# Reminding update for First Level Location
echo
echo
echo "#################################################################"
echo "Remember to Update Folder Location for First Level"
echo "This script currently uses the following location:"
indent "$First_level"
echo "To exit and reset First Level Location, push CTRL + C....."
echo "#################################################################"
echo

## Script pauses or 'sleeps' for 4 seconds, before continuing.
sleep 4 

# For loop begins
for subj in $(ls $First_level) ; do
	subj_header $subj
echo "Checking volume coverage and average intensity between ${roi#/nfs/turbo/ahrb-data/Demidenko/masks/} & $con...."

	# Requesting volumes using fslstats of $roi, printing only the fisrt column of output
	roi_vol=$(fslstats $roi -V | awk '{ print $1 }')
		indent "ROI volumes: $roi_vol"

	# Reqiesting volume coverage diff between $con & $roi for each subject, storing first column value
	con_vol=$(fslstats $First_level/$subj/FirstLevel_iso/$con -k $roi -V | awk '{ print $1 }')
		indent "$2 volumes in ROI: $con_vol"
	
	# Calculating ratio of coverage 
	ratio=$(perl -e "print $con_vol/$roi_vol" | cut -c1-4)
		indent "Volume coverage: $ratio"

	# Calculating signal intensity in location of roi in con 
	sig_intensity=$(fslmeants -i $First_level/$subj/FirstLevel_iso/$con -m $roi)
		indent "Signal Intensity in ROI: $sig_intensity"
done

