#!/bin/bash


roi=/nfs/turbo/ahrb-data/Demidenko/masks/$1
con=$2

First_level=/nfs/turbo/ahrb-data/Demidenko/FirstLevel2/mid

# When the dimensions are incorrect, run below 
#3dresample -master  $con -input $roi -prefix $roi 

if [ $# -lt 2 ] ; then
		echo "This script requires an ROI and CON file name"
		echo "Example: to run this script for R_Amyg.nii & con_0001.nii, do the  enter:"
		echo "$0 R_Amyg.nii con_0001.nii"
		echo
	exit
fi

for subj in $(ls $First_level) ; do
echo "Calculating volumes for $subj...."
xroi_vol=$(fslstats $roi -V | awk '{ print $1 }')
echo "ROI volumes: $roi_vol"
con_vol=$(fslstats $First_level/$subj/FirstLevel/$con -k $roi -V | awk '{ print $1 }')
echo "$2 volumes in ROI: $con_vol"

ratio=$(perl -e "print $roi_vol/$con_vol" | cut -c1-4)
echo "$ratio"
done

