#!/bin/bash

ahrb=/nfs/turbo/ahrb-data/archive_dir
work_dir=/nfs/turbo/ahrb-data/archive_dir
subj=$(ls $ahrb)


# DTI is measure of structural connectivity. We're trying to get a sense of direction of flow in the white matter (WM) -- the fatty substance. 
# The white matter substance has preferred directions, so we are able to diffuse water alone these tracts. It will diffuse in the orientation of the fiber.
# 		Isotropy = no preferred direction; Anisotropy = preferred direction of diffusion. In DTI, we focus on the high anisotropy of water molecules along WM tracts (fibers)


# DTI needs to be converted from dicom to nifti files. Multi-band requires a conversation process that is dependent on the MB factor, which is not relevant to single EPI acquisition
#	you need bval, bvec and dti file. 
#		these provide direction of diffusion and amount of diffusion along specific voxel or tract

# Step 1: Motion correction, eddy current correction

# Step 2: DTI fit, reconstruct the diffusion tensors (where predominant diffusion is going along fibers)
	# use the diffusion weighted image
	# create and use a BET mask
	# bvec files
	# bval files
		# once process is completed, the regular tensor fitting is completed.

# Step 3: Can review the DTI values in fslview


# Preprocessing step 1: correct for distortions and/or any motion in acquisition (using fieldmaps in magnetic field)
	# step 1a: correcting for distortions when acquiring DTI, using topup. Need bvec, bvals, acqparams.txt(AC to PC or readout time)
	# use diffusion weight data and the nodif_PA info (AC to PC and PC to AC, need both)
		# extra first image of first image of DTI data	
			fslroi dwidata.nii.gz nodif 0 1
		# then merge the two
			fslmerge -t AP_PA_b0 nodif nodif_PA

		# then run topup to run estimations. Requires the image (AP_PA, image that was combo of diff encoding directions) in file and parameter file (scanner tech provides), 
		# config (output, but not essential), out (output dataset). Takes some time to run.
			topup --imain=AP_PA_b0 --datain=acqparams.txt --config=b02b0.cnf --output=topup_AP_PA_b0

	
		# if you open fslview that had topup applied to it (distortions mapped out), you see the distortion effects, and we do reverse to get cleaner image. No need to review, but use these estimates
		
		# once an estimate map exists, we have parameters that contain any distortions. Now this has to be used with eddycurrent correction
		
		# first run bet extraction
			bet hifi_nodif hifi_nodif_brain -m -f 0.2
		
		# then run eddycurrnet command. Applies the mask created above, index command where acquisition parameters hold (1 for each row for each volume), defaults: fwhm = 0, nos moothing in step
			# flm = quadratic, good default and don't want to change; topup = file with suseptibility of artifacts in dti field
			eddy --imain=dwidata --mask=hifi_nodif_brain_mask --indix=index.txt --acqp=acqparams.txt --bvecs=bvecs --bvals=bvals --fwhm=0 --topup=topup_AP_PA_b0 --flm=quadratic --out=eddu_unwarped_images

			# can do before and after comparison. dwidata = original with artificats, then look at eddy_unwarped_image (which does equivalent to motion and distortion corrections)


# Creating and fitting tensors. This creates the [FA anisotropy maps]
	# use fsl gui to do DTIFIT reconstructu diffusion tensors
		# specify input = 1) eddyunwarped images; 2) mask from bet e.g., hifi_nodif_brain_mask, bvel, bvac files
		# hit go, runs quickly. Then check in fslview to make sure nothing went wrong. 
			# flsview open dti_fa.nii and dti_v1.nii -- click i, image type = DT, display RGB, and modulated by dti_fa (brightest is where diffusion is greatest into a direction)


# After preprocessing and FA anisotropy maps are generated. Now performed Tract Based Spatial Statistics (TBSS). 
	# Step 1: After we hae FA maps, put them all in a single directory. The FA maps .nii files are the maps that have been processed for the subjects. 
	# tbss steps
		# Step 1: apply the first tbss preproc step on all subjects FA maps. tbss preproc will do erosion of masks to rid of artificants in maps, 
			tbss_1_preproc *.nii.gz
				# will finish, then review data in FA directory and slicesdir. Open with firefox
					open -a firefox slidesdir/index.html
						# is anything gone horribly wrong?

		# Step 2: run in FA directory: tbss_2_reg used recommended options -T (takes a while)  
			tbss_2_reg -T
		
		# step 3: & tbss_3_postreg - normalizing to standardized space.. run from directory above FA -S mean_FA_skeleton. Runs a while, creates a stats directory. Creates a mean_FA.nii map 	
			tbss_3_postreg -S
		
				# Make sure the pathways don't encrach on CSF or gray matter: fslview $MNItemplate mean_FA.nii.gz -l Red-Yellow -b 0.2,0.6
				# review the merged FA maps for all: fsvliew all_FA mean_FA_skeleton -l Green -b 0.2,0.6 
						# highlight all FA, volume 0 = first subject, volume 1 = subject 1, etc. If you click through, you see how it overlaps on all subjects. Looking at WM?

		# Step 4: tbss_4_prestats - does the same thresholding that you do for masks... this thresholds the skeleton and does distance estimation of the skeleton (not strange connections between WM)
			tbss_4_prestats 0.2
								
			# if used recommended threshold of 0.2. Look at output of fslview (output in stats directory) 
				fslview all_FA_skeletonized.nii.gz 
				# look that there is good alignment, and the data is sensible. Go through volumes (i.e., subjects). Can turn on movie mode (options, MISC tab, frame rate, 500ms)


# Randomize and create a contrast matrics to compare differences of tractography. 
		# Step 1: from stats directory, use FSL to create a design & contrasts (GLM gui - higher-level, # inputs = subjects). Wizard, two groups, unpaired (then everything is generated)
				# contrasts, 2: younger > older & older > younger
				# then save the file out as design.
	
			# now have design.con and design.mat
		# Step 2: run randomize on design con and mat files (if clustering = -c 1.5, threshold of t=1.5)
			randomise -i all_FA_skeletonised.nii.gz -o tbss -m mean_FA-skeleton_mask -d design.mat -t design.con -c 1.5

				# creates cluster correct maps. tbss_clustere_corrp_tstat1.nii.gz would be younger > older (where diffusion is greater for one group compared to other)
		# Step 3: to make nice figured, use tbss_fill (0.949 = clusters only where significance is = .05). This will generate a file you can open in fslview
			tbss_fill tbss_cluster_corrp_tstat1 0.949 mean_FA tbss_clusterte_corrp_tstat1_filled
				# open image... open standardized space image, MNI, then on top add filled image created. You will see any places of WM tractography between two populations.
