#!/bin/bash

ds008=$HOME/Projects/ds008

cd $ds008
subjects=$(ls -d sub???)
date=$(date +%F_%T)

    # the below searchers variable, searching in all subjects in subjects BOLD for  bold.nii.gz
    for bold_file in $(find $subjects/BOLD -name bold.nii.gz) ; do
        #then runs fslinfo command for every bold.nii.gz, isolating anything with "dim"
            dims=$(fslinfo $bold_file | grep 'dim')
            bold_dim1=$(echo $dims | awk  '{ print $2 }')
            bold_dim2=$(echo $dims | awk  '{ print $4 }')
            bold_dim3=$(echo $dims | awk  '{ print $6 }')
            bold_dim4=$(echo $dims | awk  '{ print $8 }')
            bold_pdim1=$(echo $dims | awk '{ print $10 }')
            bold_pdim2=$(echo $dims | awk '{ print $12 }')
            bold_pdim3=$(echo $dims | awk '{ print $14 }')
            bold_pdim4=$(echo $dims | awk '{ print $16 }')
		echo "======================================================================================"
                echo "Header Values Extracted on: $date"
            printf "%7s %20s     dim1 = %8d    dim2 = %8d    dim3 = %8d   dim4 = %8d\n" \
                   "$bold_file" $bold_dim1 $bold_dim2 $bold_dim3 $bold_dim4
            printf "%7s %20s    pdim1 = %8f   pdim2 = %8f   pdim3 = %8f  pdim4 = %8f\n" \
                  "$bold_file" $bold_pdim1 $bold_pdim2 $bold_pdim3 $bold_pdim4 
         done

