#!/bin/bash
Projects=$HOME/Projects
mri=$HOME/Projects/ds008

#if command is true, exists saying folder exists.
cd $mri
subjects=$(ls -d sub???)

for subject in $subjects ; do
	for id in {001..015} ; do
		if [ -s $mri/$subject/anatomy/highres${id}_brain.nii.gz ] ; then
		fslview $mri/$subject/anatomy/highres${id}_brain.nii.gz 
		fi	
done
done

