#!/bin/bash

project_dir="$HOME/Projects"
data_dir="$project_dir/ds008"

if [ -z "$1" ] ; then
    echo "You must supply a subject folder name."
    echo
    echo "Usage: setup-tmp-subject sub001"
    echo
    exit 1
fi

cd $data_dir || exit 1

if [ ! -d "$data_dir/$1" ] ; then
    echo
    echo "Invalid subject folder name given."
    echo
    ls -ld $data_dir/$1
    echo
    exit 1
fi

if [ ! -d "$project_dir/tmp" ] ; then
    echo
    echo "Creating $project_dir/tmp"
    echo
fi

if [ -d "$project_dir/tmp/$1" ] ; then
    echo
    echo "$project_dir/tmp/$1 exits.  Please delete it and rerun."
    echo
    exit 1
fi
echo
echo "Copying $data_dir/$1 to $project_dir/tmp/$1"
# NOTE:  The trailing slash on $project_dir/tmp/ is required to indicate
#        that $1 should go _inside_ it, not become $project_dir/tmp.
cp -r $data_dir/$1 $project_dir/tmp/
echo
echo "Done"
echo
